version: '3'

services:
  liable:
    build:
      context: .
      args:
        - PYTHON3_VERSION=${PYTHON3_VERSION}
    image: lycantropos/liable:0.0.3
    volumes:
      - ./liable/:/opt/liable/liable/
      - ./tests/:/opt/liable/tests/
      - ./README.rst:/opt/liable/README.rst
      - ./setup.py:/opt/liable/setup.py
      - ./setup.cfg:/opt/liable/setup.cfg
      - ./run-plain-tests.sh:/opt/liable/run-plain-tests.sh
    entrypoint: /opt/liable/run-plain-tests.sh
    command:
      - -r
      - liable
    extra_hosts:
      - "dockerhost:$DOCKERHOST"  # for debugging
